### ISSUE TITLE
Improve error report detail

### ISSUE THREAD

**Issue by f3flight** [adobdin/timmy#21]
Example:

```
[root@fuel timmy]# ./timmy.py
2016-05-09 19:12:20,694 ERROR load_conf: I/O error(2): No such file or directory
[root@fuel timmy]#
```

It's not clear which file is missing. We need to try showing more details for errors.

**Comment by adobdin** [comment]
Implemented https://github.com/adobdin/timmy/commit/d872c533f43cf9c243c46b8d7a19c4608f57254c

**Comment by f3flight** [comment]
Let's keep open until merged to master
