### ISSUE TITLE
improve logging

### ISSUE THREAD

**Issue by f3flight** [adobdin/timmy#25]
- change loglevel from info to verbose for most messages
- add info level logs for major operations (like start-end of run_commands, get_files, get_logs)
- change default verbosity to info to show progress during execution

**Comment by adobdin** [comment]
also could be helpful to add some attributes from https://docs.python.org/2/library/logging.html#logrecord-attributes

**Comment by f3flight** [comment]
need to make warnings cleaner (when a command exited non-zero) - show node id, name, ip, and stderr, all in one line.
Done in https://github.com/adobdin/timmy/commit/7620309cc8ceaaa14216f2c45b19d9ec3c745f46
