### ISSUE TITLE
Add to the documentation usual workflow

### ISSUE THREAD

**Issue by aepifanov** [adobdin/timmy#28]
I want to get some set of logs and output from some set of commands:
- I should provide some set of files (configs and etc)
- I should provide a set of command

**Comment by f3flight** [comment]
Please check https://github.com/adobdin/timmy/blob/master/doc/source/usage.rst
Is this sufficient?

**Comment by f3flight** [comment]
Closing for now since this has been merged. @aepifanov please review the current documentation (link above)
