### ISSUE TITLE
Update / improve documentation

### ISSUE THREAD

**Issue by adobdin** [adobdin/timmy#5]

**Comment by f3flight** [comment]
Do we have a good enough readme? Closing?

**Comment by f3flight** [comment]
need to fix README.md and add installation guide and links to other docs

**Comment by f3flight** [comment]
usage.rst:
- add -c for --config
  -R, --role - change to small "r"
- split actions and options
- for actions explain shell mode better, put on top, remove "enables shell mode" from each parameter

**Comment by f3flight** [comment]
some improvement for configuration doc - https://github.com/adobdin/timmy/commit/9b6605aeeccbf9565559fa496bfebfd8fb637a6d
