### ISSUE TITLE
RuntimeWarning: Parent module 'df' not found while handling absolute import

### ISSUE THREAD

**Issue by adobdin** [adobdin/timmy#70]
There a lof of messages related to import python code for analyze module.
`RuntimeWarning: Parent module 'df' not found while handling absolute import
  from timmy.analyze_health import GREEN, UNKNOWN, YELLOW, RED`

**Comment by f3flight** [comment]
fixed by https://github.com/openstack/timmy/commit/6988c468d8f5e9c227801d132f8a8fe45085f5ec
